### ISSUE TITLE
함수명 컨벤션 통일

### ISSUE THREAD

**Issue by daddydeveloper-j** [skyangs/Cafe-On#10]
**배경**

`heck_existCafe` 와 같이 부분적으로 camel case 와 snake case 가 혼용되어 사용되고 있습니다.
메서드나 클래스명은 자바 컨벤션으로 camel case 를 사용하고 있기에 이를 통일 시키면 좋겠어요.

**목적**
프로젝트내 컨벤션 통일

**실행방법**
snake case 를 camel case로 변경

**Comment by skyangs** [comment]
메서드명 카멜케이스로 변경하여 pr하였습니다!
